# Generated by Django 4.1 on 2022-08-28 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('familiares_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.familiares')),
            ],
        ),
    ]
