# Generated by Django 4.1 on 2022-08-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentezco',
            name='familiares_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miembros.familiares'),
        ),
    ]
